# Generated by Django 3.0.4 on 2020-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='users')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
